version: "3.1"
services:
  db:
    image: "postgres"
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    volumes:
      - api_data:/var/lib/postgresql/data
      - ./psql_scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: secretpassword
volumes:
  api_data: